export const ServiceStatus = Object.freeze({
  AVAILABLE: 'Available',
  LIMITED: 'Limited',
  UNAVAILABLE: 'Unavailable',
});

export const ValidationCode = Object.freeze({
  INVALID_OUTAGE_DURATION: 'INVALID_OUTAGE_DURATION',
  EMPTY_TARGET_SERVICES: 'EMPTY_TARGET_SERVICES',
  DUPLICATE_TARGET_SERVICE: 'DUPLICATE_TARGET_SERVICE',
  TARGET_SERVICE_NOT_FOUND: 'TARGET_SERVICE_NOT_FOUND',
  INVALID_AVAILABILITY_NODE: 'INVALID_AVAILABILITY_NODE',
  INVALID_AVAILABILITY_VALUE: 'INVALID_AVAILABILITY_VALUE',
  MISSING_AVAILABILITY: 'MISSING_AVAILABILITY',
  SERVICE_WITHOUT_DEPENDENCIES: 'SERVICE_WITHOUT_DEPENDENCIES',
  DEPENDENCY_NOT_FOUND: 'DEPENDENCY_NOT_FOUND',
  CYCLE_DETECTED: 'CYCLE_DETECTED',
});
